#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -avP build/ rndegwa@139.162.252.21:/srv/riceblast.ilri.org/frontend/
echo "Deployment complete"